#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  setup-tokendash-dev-aliases.sh [TOKENDASH_REPO_DIR]

Examples:
  # Run from inside the tokendash repo:
  setup-tokendash-dev-aliases.sh

  # Or pass the repo path explicitly:
  setup-tokendash-dev-aliases.sh ~/Documents/Github/tokendash

This updates ~/.zshrc with two aliases:
  build-tokendash-dev  Build the local tokendash repo
  tokendash-dev        Run the built local tokendash server
USAGE
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

resolve_repo_dir() {
  if [[ $# -gt 0 && -n "${1:-}" ]]; then
    cd -- "$1" && pwd
    return
  fi

  if git_root="$(git -C "$PWD" rev-parse --show-toplevel 2>/dev/null)"; then
    printf '%s\n' "$git_root"
    return
  fi

  if [[ -f "$PWD/package.json" ]]; then
    pwd
    return
  fi

  if [[ -f "$script_dir/../../tokendash/package.json" ]]; then
    cd -- "$script_dir/../../tokendash" && pwd
    return
  fi

  echo "Could not locate tokendash repo. Run this from inside the repo or pass TOKENDASH_REPO_DIR." >&2
  exit 1
}

repo_dir="$(resolve_repo_dir "${1:-}")"
package_json="$repo_dir/package.json"
server_entry="$repo_dir/dist/server/index.js"
zshrc="${ZDOTDIR:-$HOME}/.zshrc"

if [[ ! -f "$package_json" ]]; then
  echo "No package.json found in: $repo_dir" >&2
  exit 1
fi

if ! grep -q '"tokendash"' "$package_json"; then
  echo "package.json in $repo_dir does not look like the tokendash package." >&2
  exit 1
fi

if [[ ! -f "$server_entry" ]]; then
  echo "Note: $server_entry does not exist yet. Run build-tokendash-dev before tokendash-dev." >&2
fi

mkdir -p -- "$(dirname -- "$zshrc")"
touch "$zshrc"

start_marker="# >>> tokendash-dev aliases >>>"
end_marker="# <<< tokendash-dev aliases <<<"
tmp_file="$(mktemp)"

awk -v start="$start_marker" -v end="$end_marker" '
  $0 == start { skip = 1; next }
  $0 == end { skip = 0; next }
  skip != 1 { print }
' "$zshrc" > "$tmp_file"

{
  printf '\n%s\n' "$start_marker"
  printf '# Generated by setup-tokendash-dev-aliases.sh. Re-run the script to update the path.\n'
  printf 'alias tokendash-dev=%q\n' "node \"$server_entry\""
  printf 'alias build-tokendash-dev=%q\n' "npm --prefix \"$repo_dir\" run build"
  printf '%s\n' "$end_marker"
} >> "$tmp_file"

mv "$tmp_file" "$zshrc"

cat <<DONE
Updated $zshrc

Aliases installed for:
  $repo_dir

Open a new terminal or run:
  source "$zshrc"

Then use:
  build-tokendash-dev
  tokendash-dev
DONE
